name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 7.2.0
homepage: https://github.com/cedvdb/phone_form_field
publish_to: none

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.7.3"

dependencies:
  circle_flags:
    path: packages/flutter_circle_flags
  dart_countries: ^3.0.3
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.18.0
  phone_numbers_parser: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
